### ISSUE TITLE
Where is the generative model?

### ISSUE THREAD

**Issue by ylqfp** [phreeza/keras-GAN#1]
Hi, In the original paper - generative adversarial nets, there is a generative model G, and a discriminative model D, where is your G?

**Comment by phreeza** [comment]
In general in these scripts, G is called generator, and D is called decoder.

**Comment by ylqfp** [comment]
Thanks a lot! 
I'm doing generative model such as LDA before, therefore, I'm thinking about , the generative should be like LDA form, sampling or variational inference method. This is totally different in DL.
